name: lint
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
  pull-requests: write
jobs:
  lint:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_SHELL_SHFMT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}